version: '3.9'
services:
 redis_cache:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
 spotfinder_db:
    image: postgres:latest
    environment:
     - POSTGRES_USER=pameligo
     - POSTGRES_PASSWORD=pameligo
     - POSTGRES_DB=spotfinder
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - spotfinder_data:/var/lib/postgresql/data

volumes:
 spotfinder_data:
