version: '3.9'
services:
 redis_cache:
    image: alexkal98/redis_cache:latest
    build:
      context: .
    restart: always
    ports:
      - '6379:6379'

 spotfinder_db:
    image: alexkal98/spotfinder_db:latest
    build:
      context: .
    environment:
      - POSTGRES_USER=pameligo
      - POSTGRES_PASSWORD=pameligo
      - POSTGRES_DB=spotfinder
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - spotfinder_data:/var/lib/postgresql/data

 spotfinder_app:
    image: alexkal98/spotfinder_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"
    depends_on:
      - redis_cache
      - spotfinder_db

volumes:
 spotfinder_data:
